# Generated by Django 2.2 on 2021-11-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specifics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CoreClock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CoreCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IntegratedGraphics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=30, null=True)),
                ('core_count', models.IntegerField(null=True)),
                ('smt', models.BooleanField(default=False)),
                ('boost_clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_clock', to='CPU.CoreClock')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPU.Brand')),
                ('core_clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_clock', to='CPU.CoreClock')),
                ('integrated_graphics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPU.IntegratedGraphics')),
                ('max_supported_memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.Memory')),
                ('socket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.Socket')),
                ('tdp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.TDP')),
            ],
        ),
    ]
