# Generated by Django 2.2 on 2021-11-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specifics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CoreClock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, null=True)),
                ('length', models.CharField(max_length=30, null=True)),
                ('TDP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.TDP')),
                ('boost_clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_clock', to='GPU.CoreClock')),
                ('chipset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPU.Chipset')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.Color')),
                ('core_clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_clock', to='GPU.CoreClock')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifics.Memory')),
            ],
        ),
    ]
